services:
  # 1. Database
  db:
    image: postgres:15-alpine
    container_name: vdt_supermarket_db
    environment:
      POSTGRES_USER: ${DB_USER:-supermarket_db_exvs_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-u0tGq1rZG5nb84Ek2siWlqzIDb9W8qO7}
      POSTGRES_DB: ${DB_NAME:-supermarket_db_exvs}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - demi_network
    restart: always

  # 2. Redis
  cache:
    image: redis:6-alpine
    container_name: demi_redis
    ports:
      - "6379:6379"
    networks:
      - demi_network
    restart: always

  # 3. AUTH SERVICE
  auth-service:
    build: ./backend-node/services/auth-service
    container_name: demi_auth_service
    ports:
      - "5001:5001"
    env_file: 
      - ./backend-node/services/auth-service/.env
    depends_on:
      - db
      - cache
    networks:
      - demi_network
    restart: on-failure

  # 4. PRODUCT SERVICE
  product-service:
    build: ./backend-node/services/product-service
    container_name: demi_product_service
    ports:
      - "5002:5002"
    env_file: 
      - ./backend-node/services/product-service/.env
    depends_on:
      - db
      - cache
    networks:
      - demi_network
    restart: on-failure

  # 5. CART SERVICE (Cổng 5003)
  cart-service:
    build: ./backend-node/services/cart-service
    container_name: demi_cart_service
    ports:
      - "5003:5003"
    env_file: 
      - ./backend-node/services/cart-service/.env
    depends_on:
      - db
      - cache
    networks:
      - demi_network
    restart: on-failure
    
  # 6. PAYMENT SERVICE (Cổng 5004)
  payment-service:
    build: ./backend-node/services/payment-service
    container_name: demi_payment_service
    ports:
      - "5004:5004"
    env_file: 
      - ./backend-node/services/payment-service/.env
    depends_on:
      - db
      - cache
    networks:
      - demi_network
    restart: on-failure

  # 7. Frontend
  frontend:
    build: ./frontend-web
    container_name: vdt_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - product-service
      - cart-service
    networks:
      - demi_network
    restart: always

  # 8. Uptime Kuma
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: demi_monitoring
    ports:
      - "3001:3001"
    volumes:
      - kuma_data:/app/data
    networks:
      - demi_network
    restart: always

  # 9. ORDER SERVICE (Cổng 5005)
  order-service:
    build: ./backend-node/services/order-service
    container_name: demi_order_service
    ports:
      - "5005:5005"
    env_file: 
      - ./backend-node/services/order-service/.env
    depends_on:
      - db
      - cache
    networks:
      - demi_network
    restart: on-failure

    # 10. AI SERVICE (Cổng 8000)
  ai-service:
    build: ./ai-service
    container_name: demi_ai_service
    ports:
      - "8000:8000"
    env_file:
      - ./ai-service/.env
    networks:
      - demi_network
    restart: on-failure

networks:
  demi_network:
    driver: bridge

volumes:
  pgdata:
  kuma_data: