# Cấu hình cổng chạy ứng dụng
server.port=8085

# =======================================================================
# 1. CẤU HÌNH RABBITMQ
# =======================================================================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Cấu hình Exchange & Queue phục vụ gửi Email
notification.rabbitmq.exchange=notification.exchange
notification.rabbitmq.queue.email=notification.email.queue
notification.rabbitmq.routing.email=notification.email.routing

# Cấu hình Queue phục vụ nhận sự kiện Đăng nhập (Real-time qua WebSocket)
notification.rabbitmq.queue.login=login.notification.queue

# =======================================================================
# 2. CẤU HÌNH GỬI MAIL (GMAIL SMTP)
# =======================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=voduyduydlk@gmail.com
# Lưu ý: password ở đây là "Mật khẩu ứng dụng" (App Password) được tạo từ tài khoản Google, không phải mật khẩu chính của Gmail.
spring.mail.password=bmua bicz qmxi niqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =======================================================================
# 3. CẤU HÌNH MONGODB
# =======================================================================
# Tự động kết nối và tạo cơ sở dữ liệu "supermarket_notification" trên local của bạn
spring.data.mongodb.uri=mongodb://voduyduydlk_db_user:DemiMart2026@ac-kf1htmb-shard-00-00.kozikg3.mongodb.net:27017,ac-kf1htmb-shard-00-01.kozikg3.mongodb.net:27017,ac-kf1htmb-shard-00-02.kozikg3.mongodb.net:27017/notification-service?ssl=true&replicaSet=atlas-gwlp8o-shard-0&authSource=admin&appName=DemiMartMGDB