source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'pg'
gem 'sequel'
gem 'dotenv'
gem 'json'


# 🌟 Khắc phục lỗi Sinatra khởi động (Thiếu máy chủ web)
gem 'rackup'
gem 'puma'

# 🌟 Định nghĩa tài liệu cấu trúc API cho hệ thống
gem 'swagger-blocks'